services:
  backend:
    build:
      context: ./backend
    container_name: topmate-backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://backend:8001/api
    container_name: topmate-frontend
    ports:
      - "5175:80"
    depends_on:
      - backend
    restart: unless-stopped
