"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _about from './about.bones.json'
import _ai_ml from './ai-ml.bones.json'
import _cohort from './cohort.bones.json'
import _contact from './contact.bones.json'
import _creator_dashboard from './creator-dashboard.bones.json'
import _creator_home from './creator-home.bones.json'
import _design from './design.bones.json'
import _home from './home.bones.json'
import _marketplace from './marketplace.bones.json'
import _meeting from './meeting.bones.json'
import _pricing from './pricing.bones.json'
import _priority_dm from './priority-dm.bones.json'
import _privacy from './privacy.bones.json'
import _product_management from './product-management.bones.json'
import _search_services from './search-services.bones.json'
import _search from './search.bones.json'
import _seeker_dashboard from './seeker-dashboard.bones.json'
import _seeker_home from './seeker-home.bones.json'
import _signin from './signin.bones.json'
import _signup from './signup.bones.json'
import _signup2 from './signup2.bones.json'
import _signup3 from './signup3.bones.json'
import _signup4 from './signup4.bones.json'
import _signup5 from './signup5.bones.json'
import _software_engineer from './software-engineer.bones.json'
import _terms from './terms.bones.json'
import _webinar from './webinar.bones.json'

registerBones({
  "about": _about,
  "ai-ml": _ai_ml,
  "cohort": _cohort,
  "contact": _contact,
  "creator-dashboard": _creator_dashboard,
  "creator-home": _creator_home,
  "design": _design,
  "home": _home,
  "marketplace": _marketplace,
  "meeting": _meeting,
  "pricing": _pricing,
  "priority-dm": _priority_dm,
  "privacy": _privacy,
  "product-management": _product_management,
  "search-services": _search_services,
  "search": _search,
  "seeker-dashboard": _seeker_dashboard,
  "seeker-home": _seeker_home,
  "signin": _signin,
  "signup": _signup,
  "signup2": _signup2,
  "signup3": _signup3,
  "signup4": _signup4,
  "signup5": _signup5,
  "software-engineer": _software_engineer,
  "terms": _terms,
  "webinar": _webinar,
})
